version: '3'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 9999:80
      - 443:443
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx.conf/:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true
